# docker-compose file to run golang server
version: '3'
services:
  auth:
    build:
      dockerfile: ./apps/auth/Dockerfile
      context: .
      target: dev
    container_name: auth_app
    hostname: auth_api
    working_dir: /github.com/eduaravila/momo/apps/auth
    command: sh -c "air -c .air.toml"
    environment:
      - ENV=development
    env_file:
      - .env.development
    volumes:
      - ./apps/auth:/github.com/eduaravila/momo/apps/auth
    ports:
      - "8080:8080"
      - "4000:4000"
    restart: always
    networks:
      - postgres_auth
    depends_on:
      - postgres_auth
  postgres_auth:
    container_name: postgres_auth
    image: postgres:15.1-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: always
    networks:
      - postgres_auth
    volumes:
      - postgresdata:/var/lib/postgresql/data
  redis:
    image: redis:6.2.1-alpine
    ports:
      - "6379:6379"
    restart: always

networks:
  postgres_auth:
    name: postgres_auth_network
    driver: bridge
volumes:
  postgresdata:
    driver: local
