# docker-compose file to run golang server
version: '3'
services:
  auth-grpc:
    build:
      dockerfile: ./apps/auth/Dockerfile
      context: .
      target: dev
    container_name: auth-grpc-app
    hostname: auth-grpc-app 
    working_dir: /github.com/eduaravila/momo/apps/auth
    command: sh -c "air -c .air-grpc.toml"
    environment:
      - ENV=development
    env_file:
      - .env.development
    volumes:
      - ./apps/auth:/github.com/eduaravila/momo/apps/auth
    ports:
      - "3002:3002"
    restart: always
    networks:
      - postgres-auth
    depends_on:
      - postgres-auth

  auth-http:
    build:
      dockerfile: ./apps/auth/Dockerfile
      context: .
      target: dev
    container_name: auth-http-app
    hostname: auth-http-app 
    working_dir: /github.com/eduaravila/momo/apps/auth
    command: sh -c "air -c .air-http.toml"
    environment:
      - ENV=development
    env_file:
      - .env.development
    volumes:
      - ./apps/auth:/github.com/eduaravila/momo/apps/auth
    ports:
      - "3001:3001"
    restart: always
    networks:
      - postgres-auth
    depends_on:
      - postgres-auth
  postgres-auth:
    container_name: postgres-auth
    image: postgres:15.1-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: always
    networks:
      - postgres-auth
    volumes:
      - postgresdata:/var/lib/postgresql/data
  redis:
    image: redis:6.2.1-alpine
    ports:
      - "6379:6379"
    restart: always

networks:
  postgres-auth:
    name: postgres-auth-network
    driver: bridge
volumes:
  postgresdata:
    driver: local
