# docker-compose file to run golang server
version: '3'
services:
  auth_debug:
    build:
      dockerfile: ./apps/auth/Dockerfile
      context: .
      target: debug
    container_name: auth_app_debug
    hostname: auth_api
    working_dir: /github.com/eduaravila/momo/apps/auth
    environment:
      - ENV=development
      - DB_HOST=postgres 
    env_file:
      - .env.development
    volumes:
      - ./apps/auth:/github.com/eduaravila/momo/apps/auth
    ports:
      - "8081:8080"
      - "4001:4000" 
    restart: always
    depends_on:
      - postgres
  