# docker-compose file to run golang server
version: '3'
services:
  lister_development:
    build:
      context: ./apps/listener
      target: dev
    container_name: listener_development    
    hostname: listener_api
    environment:
      - ENV=development
    env_file:
      - ./apps/listener/.env.development.local
    volumes:
      - ./apps/listener:/listener/src/app
    working_dir: /app/src/app
    ports:
      - "8080:8080"
    command: sh -c "air -c .air.toml"
    restart: always
    depends_on:
      - serviceName: db
        condition: service_healthy
  db:
    build: 
      context: ./apps/db      
    container_name: db
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
  volumes:
    db:
      driver: local
  