# docker-compose file to run golang server
version: '3'
services:
  lister_development:
    build:
      context: ./apps/auth
      target: dev
    container_name: auth_development    
    hostname: auth_api
    environment:
      - ENV=development
      - DB_HOST=postgres 
    env_file:
      - ./apps/auth/.env.development.local
    volumes:
      - ./apps/auth:/auth/src/app
    working_dir: /app/src/app
    ports:
      - "8080:8080"
    command: sh -c "air -c .air.toml"
    restart: always
    depends_on:
      - postgres
  postgres:
    image: postgres:15.1-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
  migrations:
    environment:
      DATABASE_URL: postgres
    command: sh -c "ls -la && goose postgres "postgresql://postgres:postgres@postgres:5432/postgres" up"
    build:
      context: ./apps/db
    links:
      - postgres
    depends_on:
      - postgres

volumes:
  postgresdata:
    driver: local
  