// Package port provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package port

// CodeParam defines model for codeParam.
type CodeParam = string

// ScopeParam defines model for scopeParam.
type ScopeParam = string

// OauthTwitchCallbackParams defines parameters for OauthTwitchCallback.
type OauthTwitchCallbackParams struct {
	// Code OAuth code
	Code CodeParam `form:"code" json:"code"`

	// Scope OAuth scope
	Scope ScopeParam `form:"scope" json:"scope"`
}
