// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: accounts.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const accountExistByEmail = `-- name: AccountExistByEmail :one
SELECT EXISTS (SELECT 1 FROM accounts WHERE email = $1)
`

func (q *Queries) AccountExistByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, accountExistByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const accountExistBySub = `-- name: AccountExistBySub :one
SELECT EXISTS (SELECT 1 FROM accounts WHERE sub = $1)
`

func (q *Queries) AccountExistBySub(ctx context.Context, sub string) (bool, error) {
	row := q.db.QueryRowContext(ctx, accountExistBySub, sub)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAccounts = `-- name: CountAccounts :one
SELECT COUNT(*) FROM accounts
`

func (q *Queries) CountAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id,
    name,
    picture,
    email,
    sub,
    prefered_username,
    access_token,
    refresh_token,
    iss,
    expired_at,
    scope
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)ON CONFLICT (sub) DO UPDATE SET
    name = $2,
    picture = $3,
    email = $4,
    prefered_username = $6,
    access_token = $7,
    refresh_token = $8,
    iss = $9,
    expired_at = $10,
    scope = $11 
    RETURNING id
`

type CreateAccountParams struct {
	ID               uuid.UUID
	Name             string
	Picture          string
	Email            string
	Sub              string
	PreferedUsername string
	AccessToken      string
	RefreshToken     string
	Iss              string
	ExpiredAt        time.Time
	Scope            string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.ID,
		arg.Name,
		arg.Picture,
		arg.Email,
		arg.Sub,
		arg.PreferedUsername,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Iss,
		arg.ExpiredAt,
		arg.Scope,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, picture, email, sub, prefered_username, access_token, refresh_token, iss, created_at, expired_at, scope FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Picture,
		&i.Email,
		&i.Sub,
		&i.PreferedUsername,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Iss,
		&i.CreatedAt,
		&i.ExpiredAt,
		&i.Scope,
	)
	return i, err
}

const getAccountsByIDs = `-- name: GetAccountsByIDs :many
SELECT id, name, picture, email, sub, prefered_username, access_token, refresh_token, iss, created_at, expired_at, scope FROM accounts WHERE id = ANY($1)
`

func (q *Queries) GetAccountsByIDs(ctx context.Context, id uuid.UUID) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAccountsByIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Picture,
			&i.Email,
			&i.Sub,
			&i.PreferedUsername,
			&i.AccessToken,
			&i.RefreshToken,
			&i.Iss,
			&i.CreatedAt,
			&i.ExpiredAt,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountsByISS = `-- name: GetAccountsByISS :many
SELECT id, name, picture, email, sub, prefered_username, access_token, refresh_token, iss, created_at, expired_at, scope FROM accounts WHERE iss = $1
`

func (q *Queries) GetAccountsByISS(ctx context.Context, iss string) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAccountsByISS, iss)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Picture,
			&i.Email,
			&i.Sub,
			&i.PreferedUsername,
			&i.AccessToken,
			&i.RefreshToken,
			&i.Iss,
			&i.CreatedAt,
			&i.ExpiredAt,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, picture, email, sub, prefered_username, access_token, refresh_token, iss, created_at, expired_at, scope FROM accounts
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Picture,
			&i.Email,
			&i.Sub,
			&i.PreferedUsername,
			&i.AccessToken,
			&i.RefreshToken,
			&i.Iss,
			&i.CreatedAt,
			&i.ExpiredAt,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts SET updated_at = now() WHERE id = $1
`

func (q *Queries) UpdateAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateAccount, id)
	return err
}
