// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID               uuid.UUID
	Name             string
	Picture          string
	Email            string
	Sub              string
	PreferedUsername string
	AccessToken      string
	RefreshToken     string
	Iss              string
	CreatedAt        time.Time
	ExpiredAt        time.Time
	Scope            string
}

type Configuration struct {
	ID                    uuid.UUID
	AccountID             uuid.UUID
	MaxMessageLength      int32
	MinAmountTip          int32
	MinPointTip           int32
	FallbackVoice         uuid.UUID
	IsChannelPointEnabled bool
	IsTippingEnabled      bool
	IsBitsEnabled         bool
	IsSubEnabled          bool
	IsDonationEnabled     bool
	IsCommandEnabled      bool
	IsChatEnabled         bool
	IsFollowingEnabled    bool
	IsHostingEnabled      bool
	BannedWordFileID      uuid.UUID
}

type ConfigurationsVoicesBannedJoin struct {
	ConfigurationID uuid.UUID
	VoiceID         uuid.UUID
}

type File struct {
	ID        uuid.UUID
	FileName  string
	FilePath  string
	FileType  string
	CreatedAt time.Time
}

type Issuer struct {
	Name      string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Message struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	Message     string
	CreatedAt   time.Time
	AudioFileID uuid.NullUUID
	AuthorName  string
}

type Overlay struct {
	ID        uuid.UUID
	IsBanned  bool
	IsEnabled bool
	AccountID uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Permission struct {
	ID          int32
	Name        string
	Description sql.NullString
}

type Role struct {
	ID          int32
	Name        string
	Description sql.NullString
}

type RolePermission struct {
	RoleID       int32
	PermissionID int32
}

type Session struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	CreatedAt    time.Time
	ExpiredAt    time.Time
	SessionToken string
	IpAddress    string
	UserAgent    string
	IsValid      bool
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserAccountsJoin struct {
	UserID    uuid.UUID
	AccountID uuid.UUID
	RoleID    int32
}

type Voice struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}
